#!/bin/bash

echo "🧪 Pi-Mono Java - 手动测试指南"
echo "==============================="
echo ""

echo "由于macOS环境限制，我们需要手动测试。请按以下步骤操作："
echo ""

echo "📋 测试步骤："
echo ""

echo "1️⃣ CLI功能测试"
echo "---------------"
echo "运行以下命令启动CLI："
echo "   mvn -pl pi-cli exec:java -Dexec.mainClass=\"com.pi.mono.cli.PiCliApplication\""
echo ""
echo "在CLI中依次输入："
echo "   今天天气很好"
echo "   /save"
echo "   /sessions"
echo "   exit"
echo ""
echo "✅ 预期结果："
echo "   - 应该看到'会话保存成功'消息"
echo "   - 应该显示会话列表"
echo "   - .pi/sessions目录应该有文件"
echo ""

echo "2️⃣ Spring Boot集成测试"
echo "-----------------------"
echo "进入示例项目目录："
echo "   cd example-project"
echo ""
echo "运行Spring应用："
echo "   mvn spring-boot:run"
echo ""
echo "✅ 预期结果："
echo "   - 应该看到'会话创建成功'消息"
echo "   - 应该看到AI响应"
echo "   - 应该看到'会话已保存'消息"
echo "   - .pi/sessions目录应该有文件"
echo ""

echo "3️⃣ 验证会话文件"
echo "---------------"
echo "检查生成的会话文件："
echo "   ls -la .pi/sessions/"
echo "   cat .pi/sessions/*.jsonl"
echo ""
echo "✅ 预期结果："
echo "   - JSONL格式正确"
echo "   - 包含消息内容"
echo "   - 时间戳正确"
echo ""

echo "4️⃣ 清理测试环境"
echo "---------------"
echo "清理之前的测试文件："
echo "   rm -rf .pi/sessions"
echo ""

echo "🎯 测试完成后，请告诉我结果："
echo "   - CLI是否正常工作？"
echo "   - Spring集成是否正常？"
echo "   - 会话文件是否正确生成？"
echo ""

echo "📝 如果测试失败，请提供错误信息，我会立即修复。"