package com.pi.mono.llm.mock;

import com.pi.mono.core.*;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ThreadLocalRandom;
import java.util.Map;

/**
 * Mock LLM Provider - 用于测试和开发
 */
@Component
public class MockLLMProvider implements LLMProvider {

    private static final String PROVIDER_ID = "mock-claude";

    @Override
    public CompletableFuture<AgentMessage> chat(ChatRequest request) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                // 模拟API延迟
                Thread.sleep(ThreadLocalRandom.current().nextInt(500, 2000));

                String response = generateMockResponse(request);
                return new AgentMessage(
                    MessageRole.ASSISTANT,
                    response,
                    Map.of(
                        "provider", PROVIDER_ID,
                        "model", request.options().model(),
                        "timestamp", System.currentTimeMillis(),
                        "mock", true
                    )
                );
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new RuntimeException("Request interrupted", e);
            }
        });
    }

    @Override
    public List<Model> getAvailableModels() {
        return List.of(
            new Model("mock-claude-sonnet", PROVIDER_ID, "Mock Claude Sonnet", 100000, new BigDecimal("0.001")),
            new Model("mock-claude-haiku", PROVIDER_ID, "Mock Claude Haiku", 200000, new BigDecimal("0.0005")),
            new Model("mock-gpt-4", PROVIDER_ID, "Mock GPT-4", 128000, new BigDecimal("0.002"))
        );
    }

    @Override
    public ToolCallResult executeToolCall(ToolCall toolCall, List<AgentMessage> context) {
        // Mock工具调用结果
        return new ToolCallResult(
            toolCall.name(),
            "Mock tool execution result for: " + toolCall.name(),
            Map.of("mock", true, "tool_call_id", toolCall.id())
        );
    }

    @Override
    public HealthStatus health() {
        return HealthStatus.HEALTHY;
    }

    @Override
    public boolean isAvailable() {
        return true;
    }

    @Override
    public BigDecimal getCostPerToken() {
        return new BigDecimal("0.001");
    }

    @Override
    public String getId() {
        return PROVIDER_ID;
    }

    private String generateMockResponse(ChatRequest request) {
        String lastMessage = request.messages().isEmpty() ? "" :
            request.messages().get(request.messages().size() - 1).content();

        // 根据输入生成不同的响应
        if (lastMessage.toLowerCase().contains("hello")) {
            return "Hello! I'm a mock AI assistant. How can I help you today?";
        } else if (lastMessage.toLowerCase().contains("code")) {
            return "Here's some mock code:\n\n```java\npublic class MockExample {\n    public static void main(String[] args) {\n        System.out.println(\"Hello from mock provider!\");\n    }\n}\n```";
        } else if (lastMessage.toLowerCase().contains("test")) {
            return "This is a test response from the mock LLM provider. The response time was simulated to mimic real API latency.";
        } else {
            return "I understand you said: \"" + lastMessage + "\"\n\nThis is a mock response generated by the pi-mono-java mock provider. In a real implementation, this would be replaced with actual LLM responses.";
        }
    }
}